server:
  port: 9084

spring:
  application:
    name: ignored
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus