server:
  port: 8083
spring:
  application:
    name: proxy

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        enabled: false

zuul:
  ignoredServices: 'ignored'
  routes:
    allowed:
      serviceId: ignored
      path: /test/allowed