server:
  port: 8083
spring:
  application:
    name: proxy

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug
turbine:
  aggregator:
    clusterConfig: proxy-hystrix-aggregate
    appConfig: proxy-hystrix-aggregate

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        enabled: false
zuul:
  ignored-services: 'ignored-service'