spring:
  application:
    name: card-service
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include: metrics