spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  level:
    org.springframework: info
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus